[2024-05-06T19:03:31.646-0500] {processor.py:161} INFO - Started process (PID=26907) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:03:31.646-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:03:31.647-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:03:31.647-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:03:31.675-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:03:31.675-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:03:31.676-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:03:31.675-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:03:31.676-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:03:31.740-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2024-05-06T19:06:45.622-0500] {processor.py:161} INFO - Started process (PID=27603) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:06:45.623-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:06:45.623-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:06:45.623-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:06:45.657-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:06:45.657-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:06:45.658-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:06:45.658-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:06:45.658-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:06:45.730-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-05-06T19:10:11.406-0500] {processor.py:161} INFO - Started process (PID=28336) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:10:11.407-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:10:11.407-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:10:11.407-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:10:11.436-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:10:11.435-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:10:11.436-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:10:11.436-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:10:11.436-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:10:11.498-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-05-06T19:13:46.944-0500] {processor.py:161} INFO - Started process (PID=29100) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:13:46.945-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:13:46.946-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:13:46.946-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:13:46.987-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:13:46.986-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:13:46.987-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:13:46.987-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:13:46.987-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:13:47.071-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.130 seconds
[2024-05-06T19:18:16.509-0500] {processor.py:161} INFO - Started process (PID=30129) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:18:16.511-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:18:16.512-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:18:16.511-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:18:16.552-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:18:16.551-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:18:16.552-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:18:16.552-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:18:16.552-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:18:16.637-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.131 seconds
[2024-05-06T19:22:36.301-0500] {processor.py:161} INFO - Started process (PID=31030) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:22:36.302-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:22:36.303-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:22:36.303-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:22:36.348-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:22:36.347-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:22:36.349-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:22:36.349-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:22:36.349-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:22:36.450-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.152 seconds
[2024-05-06T19:24:50.846-0500] {processor.py:161} INFO - Started process (PID=31520) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:24:50.846-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:24:50.847-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:24:50.847-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:24:50.883-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:24:50.882-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:24:50.883-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:24:50.883-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:24:50.884-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:24:50.960-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-05-06T19:27:01.949-0500] {processor.py:161} INFO - Started process (PID=31981) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:27:01.950-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:27:01.950-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:27:01.950-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:27:01.980-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:27:01.979-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:27:01.980-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:27:01.980-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:27:01.980-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:27:02.043-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2024-05-06T19:30:31.275-0500] {processor.py:161} INFO - Started process (PID=32734) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:30:31.276-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:30:31.276-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:30:31.276-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:30:31.312-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:30:31.311-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:30:31.312-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:30:31.312-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:30:31.313-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:30:31.389-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.117 seconds
[2024-05-06T19:33:55.403-0500] {processor.py:161} INFO - Started process (PID=33471) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:33:55.404-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:33:55.404-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:33:55.404-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:33:55.437-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:33:55.436-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:33:55.437-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:33:55.437-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:33:55.437-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:33:55.507-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-05-06T19:37:18.621-0500] {processor.py:161} INFO - Started process (PID=34281) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:37:18.622-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:37:18.622-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:37:18.622-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:37:18.652-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:37:18.652-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:37:18.652-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:37:18.652-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:37:18.652-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:37:18.715-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2024-05-06T19:40:39.620-0500] {processor.py:161} INFO - Started process (PID=34989) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:40:39.621-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:40:39.621-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:40:39.621-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:40:39.649-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:40:39.648-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:40:39.649-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:40:39.649-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:40:39.649-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:40:39.712-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-05-06T19:43:55.931-0500] {processor.py:161} INFO - Started process (PID=35686) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:43:55.932-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:43:55.932-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:43:55.932-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:43:55.961-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:43:55.961-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:43:55.961-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:43:55.961-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:43:55.962-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:43:56.024-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-05-06T19:47:30.804-0500] {processor.py:161} INFO - Started process (PID=36451) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:47:30.804-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:47:30.805-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:47:30.805-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:47:30.833-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:47:30.833-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:47:30.833-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:47:30.833-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:47:30.834-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:47:30.895-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-06T19:50:54.913-0500] {processor.py:161} INFO - Started process (PID=37269) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:50:54.914-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:50:54.914-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:50:54.914-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:50:54.947-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:50:54.947-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:50:54.948-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:50:54.948-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:50:54.948-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:50:55.019-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-05-06T19:54:26.727-0500] {processor.py:161} INFO - Started process (PID=38025) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:54:26.728-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:54:26.728-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:54:26.728-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:54:26.763-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:54:26.762-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:54:26.763-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:54:26.763-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:54:26.764-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:54:26.834-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2024-05-06T19:57:53.727-0500] {processor.py:161} INFO - Started process (PID=38755) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:57:53.727-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T19:57:53.728-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:57:53.728-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:57:53.756-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:57:53.755-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T19:57:53.756-0500] {logging_mixin.py:188} INFO - [2024-05-06T19:57:53.756-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T19:57:53.756-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T19:57:53.817-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-06T20:01:32.802-0500] {processor.py:161} INFO - Started process (PID=39569) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:01:32.803-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:01:32.804-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:01:32.804-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:01:32.832-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:01:32.832-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:01:32.833-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:01:32.833-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:01:32.833-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:01:32.895-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-05-06T20:05:01.504-0500] {processor.py:161} INFO - Started process (PID=40321) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:05:01.505-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:05:01.505-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:05:01.505-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:05:01.541-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:05:01.541-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:05:01.541-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:05:01.541-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:05:01.542-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:05:01.609-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-05-06T20:08:31.986-0500] {processor.py:161} INFO - Started process (PID=41075) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:08:31.986-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:08:31.987-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:08:31.987-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:08:32.016-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:08:32.015-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:08:32.016-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:08:32.016-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:08:32.016-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:08:32.079-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2024-05-06T20:11:51.864-0500] {processor.py:161} INFO - Started process (PID=41871) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:11:51.865-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:11:51.866-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:11:51.865-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:11:51.899-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:11:51.899-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:11:51.899-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:11:51.899-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:11:51.900-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:11:51.963-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-05-06T20:15:07.471-0500] {processor.py:161} INFO - Started process (PID=42559) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:15:07.472-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:15:07.473-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:15:07.472-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:15:07.501-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:15:07.501-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:15:07.501-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:15:07.501-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:15:07.502-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:15:07.562-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-06T20:18:34.652-0500] {processor.py:161} INFO - Started process (PID=43286) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:18:34.653-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:18:34.654-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:18:34.653-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:18:34.681-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:18:34.681-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:18:34.681-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:18:34.681-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:18:34.682-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:18:34.742-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-05-06T20:22:03.829-0500] {processor.py:161} INFO - Started process (PID=44039) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:22:03.830-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:22:03.831-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:22:03.831-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:22:03.864-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:22:03.864-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:22:03.865-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:22:03.865-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:22:03.865-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:22:03.935-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-05-06T20:25:24.966-0500] {processor.py:161} INFO - Started process (PID=44749) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:25:24.967-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:25:24.967-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:25:24.967-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:25:25.000-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:25:25.000-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:25:25.001-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:25:25.001-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:25:25.001-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:25:25.073-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-05-06T20:28:51.396-0500] {processor.py:161} INFO - Started process (PID=45561) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:28:51.397-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:28:51.397-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:28:51.397-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:28:51.430-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:28:51.430-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:28:51.431-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:28:51.430-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:28:51.431-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:28:51.502-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-05-06T20:32:15.023-0500] {processor.py:161} INFO - Started process (PID=46316) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:32:15.024-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:32:15.025-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:32:15.025-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:32:15.058-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:32:15.058-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:32:15.059-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:32:15.059-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:32:15.059-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:32:15.130-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2024-05-06T20:35:37.758-0500] {processor.py:161} INFO - Started process (PID=47032) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:35:37.759-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:35:37.759-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:35:37.759-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:35:37.787-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:35:37.787-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:35:37.787-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:35:37.787-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:35:37.787-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:35:37.849-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-05-06T20:38:55.724-0500] {processor.py:161} INFO - Started process (PID=47732) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:38:55.725-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:38:55.726-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:38:55.726-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:38:55.759-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:38:55.758-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:38:55.759-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:38:55.759-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:38:55.759-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:38:55.829-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-05-06T20:42:24.936-0500] {processor.py:161} INFO - Started process (PID=48481) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:42:24.937-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:42:24.937-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:42:24.937-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:42:24.966-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:42:24.966-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:42:24.967-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:42:24.966-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:42:24.967-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:42:25.030-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2024-05-06T20:45:48.519-0500] {processor.py:161} INFO - Started process (PID=49202) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:45:48.520-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:45:48.520-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:45:48.520-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:45:48.549-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:45:48.548-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:45:48.549-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:45:48.549-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:45:48.549-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:45:48.610-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-06T20:49:19.311-0500] {processor.py:161} INFO - Started process (PID=50043) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:49:19.312-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:49:19.313-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:49:19.312-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:49:19.346-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:49:19.345-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:49:19.346-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:49:19.346-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:49:19.346-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:49:19.420-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.111 seconds
[2024-05-06T20:52:50.281-0500] {processor.py:161} INFO - Started process (PID=50783) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:52:50.282-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:52:50.282-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:52:50.282-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:52:50.312-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:52:50.311-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:52:50.312-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:52:50.312-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:52:50.312-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:52:50.374-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.095 seconds
[2024-05-06T20:56:15.321-0500] {processor.py:161} INFO - Started process (PID=51506) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:56:15.321-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:56:15.322-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:56:15.322-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:56:15.351-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:56:15.350-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:56:15.351-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:56:15.351-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:56:15.351-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:56:15.413-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-05-06T20:59:50.026-0500] {processor.py:161} INFO - Started process (PID=52270) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:59:50.027-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T20:59:50.027-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:59:50.027-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:59:50.060-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:59:50.060-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T20:59:50.061-0500] {logging_mixin.py:188} INFO - [2024-05-06T20:59:50.061-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T20:59:50.061-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T20:59:50.132-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-05-06T21:03:39.858-0500] {processor.py:161} INFO - Started process (PID=53215) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:03:39.858-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:03:39.859-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:03:39.859-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:03:39.893-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:03:39.892-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:03:39.893-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:03:39.893-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:03:39.893-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:03:39.964-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2024-05-06T21:07:03.333-0500] {processor.py:161} INFO - Started process (PID=54024) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:07:03.333-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:07:03.334-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:07:03.334-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:07:03.363-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:07:03.362-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:07:03.363-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:07:03.363-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:07:03.363-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:07:03.424-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-06T21:10:26.480-0500] {processor.py:161} INFO - Started process (PID=54733) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:10:26.480-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:10:26.481-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:10:26.481-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:10:26.509-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:10:26.509-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:10:26.509-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:10:26.509-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:10:26.510-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:10:26.572-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-05-06T21:13:52.730-0500] {processor.py:161} INFO - Started process (PID=55470) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:13:52.730-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:13:52.731-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:13:52.731-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:13:52.759-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:13:52.759-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:13:52.759-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:13:52.759-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:13:52.760-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:13:52.822-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-05-06T21:17:21.311-0500] {processor.py:161} INFO - Started process (PID=56203) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:17:21.312-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:17:21.312-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:17:21.312-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:17:21.342-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:17:21.341-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:17:21.342-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:17:21.342-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:17:21.342-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:17:21.405-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.096 seconds
[2024-05-06T21:20:52.868-0500] {processor.py:161} INFO - Started process (PID=57045) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:20:52.869-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:20:52.869-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:20:52.869-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:20:52.898-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:20:52.897-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:20:52.898-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:20:52.898-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:20:52.898-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:20:52.959-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-06T21:24:23.346-0500] {processor.py:161} INFO - Started process (PID=57778) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:24:23.347-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:24:23.347-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:24:23.347-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:24:23.376-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:24:23.376-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:24:23.376-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:24:23.376-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:24:23.376-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:24:23.438-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-05-06T21:27:54.600-0500] {processor.py:161} INFO - Started process (PID=58520) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:27:54.600-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:27:54.601-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:27:54.601-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:27:54.634-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:27:54.633-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:27:54.634-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:27:54.634-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:27:54.634-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:27:54.705-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-05-06T21:32:06.143-0500] {processor.py:161} INFO - Started process (PID=59446) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:32:06.144-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:32:06.145-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:32:06.144-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:32:06.180-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:32:06.179-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:32:06.180-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:32:06.180-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:32:06.180-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:32:06.261-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.120 seconds
[2024-05-06T21:36:46.894-0500] {processor.py:161} INFO - Started process (PID=60516) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:36:46.895-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:36:46.895-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:36:46.895-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:36:46.935-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:36:46.934-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:36:46.935-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:36:46.935-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:36:46.935-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:36:47.017-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.126 seconds
[2024-05-06T21:43:43.968-0500] {processor.py:161} INFO - Started process (PID=62051) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:43:43.970-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:43:43.971-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:43:43.970-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:43:44.012-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:43:44.012-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:43:44.013-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:43:44.012-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:43:44.013-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:43:44.107-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.142 seconds
[2024-05-06T21:44:38.418-0500] {processor.py:161} INFO - Started process (PID=62290) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:44:38.420-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:44:38.421-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:44:38.421-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:44:38.466-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:44:38.465-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:44:38.467-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:44:38.466-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:44:38.467-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:44:38.575-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.160 seconds
[2024-05-06T21:45:41.895-0500] {processor.py:161} INFO - Started process (PID=62537) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:45:41.896-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:45:41.896-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:45:41.896-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:45:41.939-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:45:41.939-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:45:41.940-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:45:41.940-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:45:41.940-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:45:42.041-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.150 seconds
[2024-05-06T21:46:41.277-0500] {processor.py:161} INFO - Started process (PID=62775) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:46:41.278-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:46:41.279-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:46:41.279-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:46:41.328-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:46:41.327-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:46:41.328-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:46:41.328-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:46:41.329-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:46:41.435-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.162 seconds
[2024-05-06T21:47:46.102-0500] {processor.py:161} INFO - Started process (PID=63036) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:47:46.103-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:47:46.104-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:47:46.104-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:47:46.155-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:47:46.154-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:47:46.155-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:47:46.155-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:47:46.156-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:47:46.281-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2024-05-06T21:50:15.293-0500] {processor.py:161} INFO - Started process (PID=63663) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:50:15.296-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:50:15.298-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:50:15.297-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:50:15.380-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:50:15.379-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:50:15.381-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:50:15.381-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:50:15.382-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:50:15.619-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.331 seconds
[2024-05-06T21:51:47.392-0500] {processor.py:161} INFO - Started process (PID=64026) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:51:47.393-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:51:47.394-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:51:47.393-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:51:47.441-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:51:47.440-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:51:47.441-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:51:47.441-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:51:47.442-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:51:47.552-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.164 seconds
[2024-05-06T21:53:04.017-0500] {processor.py:161} INFO - Started process (PID=64318) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:53:04.019-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:53:04.020-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:53:04.020-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:53:04.087-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:53:04.086-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:53:04.087-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:53:04.087-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:53:04.088-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:53:04.236-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.224 seconds
[2024-05-06T21:54:24.730-0500] {processor.py:161} INFO - Started process (PID=64639) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:54:24.732-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:54:24.733-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:54:24.733-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:54:24.823-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:54:24.822-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:54:24.824-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:54:24.824-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:54:24.825-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:54:24.996-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.271 seconds
[2024-05-06T21:55:53.507-0500] {processor.py:161} INFO - Started process (PID=65003) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:55:53.509-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:55:53.510-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:55:53.510-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:55:53.563-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:55:53.562-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:55:53.564-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:55:53.564-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:55:53.564-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:55:53.692-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.189 seconds
[2024-05-06T21:57:27.602-0500] {processor.py:161} INFO - Started process (PID=65354) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:57:27.604-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:57:27.606-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:57:27.605-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:57:27.692-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:57:27.691-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:57:27.693-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:57:27.692-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:57:27.693-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:57:27.893-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.297 seconds
[2024-05-06T21:59:13.400-0500] {processor.py:161} INFO - Started process (PID=65849) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:59:13.401-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T21:59:13.403-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:59:13.402-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:59:13.467-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:59:13.466-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T21:59:13.467-0500] {logging_mixin.py:188} INFO - [2024-05-06T21:59:13.467-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T21:59:13.468-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T21:59:13.630-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.235 seconds
[2024-05-06T22:01:18.589-0500] {processor.py:161} INFO - Started process (PID=66410) to work on /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T22:01:18.590-0500] {processor.py:830} INFO - Processing file /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-06T22:01:18.591-0500] {logging_mixin.py:188} INFO - [2024-05-06T22:01:18.591-0500] {dagbag.py:540} INFO - Filling up the DagBag from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T22:01:18.643-0500] {logging_mixin.py:188} INFO - [2024-05-06T22:01:18.642-0500] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-06T22:01:18.643-0500] {logging_mixin.py:188} INFO - [2024-05-06T22:01:18.643-0500] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-06T22:01:18.644-0500] {processor.py:842} WARNING - No viable dags retrieved from /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-06T22:01:18.776-0500] {processor.py:183} INFO - Processing /Users/paulamedina/venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.191 seconds
